<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import axios from 'axios';
import FileDropzone from '@/Components/FileDropzone.vue';
defineProps<{period?:{name:string;status:string;closes_at:string}}>();
const step=ref(1);
const form=useForm({full_name:'',nik:'',birth_place:'',birth_date:'',email:'',whatsapp:'',province:'',city:'',address:'',ktp:null as File|null,title:'',genre:'',language:'Indonesia',creation_year:new Date().getFullYear(),story:'',lyrics:'',demo_url:'',video_url:'',upload_tokens:[] as {id:string;token:string;type:'demo'|'video'}[],original_work:false,rights_approved:false,data_correct:false,terms:false,communication:false,signature_name:'',idempotency_key:crypto.randomUUID()});
const fields:Record<number,(keyof typeof form)[]>={1:['full_name','nik','birth_place','birth_date','email','whatsapp','province','city','address','ktp'],2:['title','genre','language','creation_year','story'],3:[],4:['original_work','rights_approved','data_correct','terms','communication','signature_name']};
const consentFields=['original_work','rights_approved','data_correct','terms','communication'] as const;
const consentError=ref('');
const allAccepted=computed({get:()=>consentFields.every(field=>form[field]),set:(checked:boolean)=>{consentFields.forEach(field=>form[field]=checked);consentError.value='';}});
function next(){ const missing=(fields[step.value]||[]).some(k=>!form[k]);const mediaMissing=step.value===3&&(!form.demo_url&&!form.upload_tokens.some(v=>v.type==='demo')||!form.video_url&&!form.upload_tokens.some(v=>v.type==='video'));if(step.value===4&&!allAccepted.value){consentError.value='Semua deklarasi dan persetujuan wajib dicentang.';return}if(!missing&&!mediaMissing) step.value++; }
function submit(){form.post('/registration/drafts',{preserveScroll:true});}
type UploadState={id?:string;token?:string;progress:number;status:string;error?:string};
const uploads=ref<Record<'demo'|'video',UploadState>>({demo:{progress:0,status:'idle'},video:{progress:0,status:'idle'}});
const ktpMeta=ref<{name:string;size:number}>({name:'',size:0});
const mediaMeta=ref<Record<'demo'|'video',{name:string;size:number}>>({demo:{name:'',size:0},video:{name:'',size:0}});
function selectKtp(file:File){form.ktp=file;ktpMeta.value={name:file.name,size:file.size}}
function removeKtp(){form.ktp=null;ktpMeta.value={name:'',size:0}}
async function sha256(file:File){const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('')}
async function uploadLarge(file:File,type:'demo'|'video'){
 const state=uploads.value[type];mediaMeta.value[type]={name:file.name,size:file.size};state.status='preparing';state.progress=0;state.error='';const chunkSize=2*1024*1024;
 try{const checksum=await sha256(file);const init=await axios.post('/registration/uploads/init',{type,name:file.name,mime:file.type,size:file.size,chunk_size:chunkSize,checksum});state.id=init.data.id;state.token=init.data.token;state.status='uploading';
  for(let index=0;index<init.data.total_chunks;index++){const data=new FormData();data.append('index',String(index));data.append('chunk',file.slice(index*chunkSize,Math.min(file.size,(index+1)*chunkSize)),'chunk.part');let attempt=0;while(true){try{await axios.post(`/registration/uploads/${state.id}/chunk`,data,{headers:{'X-Upload-Token':state.token}});break}catch(error){if(++attempt>=3)throw error}}state.progress=Math.round(((index+1)/init.data.total_chunks)*100)}
  await axios.post(`/registration/uploads/${state.id}/complete`,{},{headers:{'X-Upload-Token':state.token}});form.upload_tokens=form.upload_tokens.filter(item=>item.type!==type);form.upload_tokens.push({id:state.id!,token:state.token!,type});state.status='completed';
 }catch(error:any){state.status='failed';state.error=error.response?.data?.message||'Upload gagal. Coba lagi.'}
}
async function cancelUpload(type:'demo'|'video'){const state=uploads.value[type];if(state.id&&state.token)await axios.delete(`/registration/uploads/${state.id}`,{headers:{'X-Upload-Token':state.token}});form.upload_tokens=form.upload_tokens.filter(item=>item.type!==type);uploads.value[type]={progress:0,status:'idle'};mediaMeta.value[type]={name:'',size:0};}
</script>
<template><Head title="Kirim Lagu"/><div class="min-h-screen bg-[#080808] text-white"><header class="border-b border-white/10 px-5 py-5"><div class="mx-auto flex max-w-5xl justify-between"><Link href="/" class="font-display font-bold">← ORIGINAL <span class="text-orange-500">SESSIONS</span></Link><span class="text-sm text-neutral-500">Langkah {{step}} dari 5</span></div></header><main class="mx-auto max-w-3xl px-5 py-12"><div class="mb-10 h-1 overflow-hidden rounded bg-white/10"><div class="h-full bg-orange-500 transition-all" :style="{width:step*20+'%'}"></div></div><p class="eyebrow">{{period?.name||'Original Sessions'}}</p><h1 class="mt-3 font-display text-4xl font-bold">{{['Data diri','Data lagu','Demo dan video','Deklarasi & persetujuan','Review dan kirim'][step-1]}}</h1><form class="mt-10 space-y-6" @submit.prevent="step===5?submit():next()">
<template v-if="step===1"><label>Nama lengkap sesuai KTP<input v-model="form.full_name" required></label><div class="grid gap-5 md:grid-cols-2"><label>NIK<input v-model="form.nik" inputmode="numeric" minlength="16" maxlength="16" required></label><label>Tempat lahir<input v-model="form.birth_place" required></label><label>Tanggal lahir<input v-model="form.birth_date" type="date" required></label><label>Email<input v-model="form.email" type="email" required></label><label>Nomor WhatsApp<input v-model="form.whatsapp" placeholder="0812..." required></label><label>Provinsi<input v-model="form.province" required></label><label>Kota/Kabupaten<input v-model="form.city" required></label></div><label>Alamat lengkap<textarea v-model="form.address" required></textarea></label><div><p class="upload-label">Dokumen identitas</p><FileDropzone accept="image/jpeg,image/png,application/pdf" label="Upload KTP" hint="Tarik file ke sini atau klik · JPG, PNG, PDF · Maks. 10 MB" :selected-name="ktpMeta.name" :selected-size="ktpMeta.size" @select="selectKtp" @remove="removeKtp" /></div></template>
<template v-if="step===2"><label>Judul lagu<input v-model="form.title" required></label><div class="grid gap-5 md:grid-cols-2"><label>Genre utama<input v-model="form.genre" required></label><label>Bahasa lagu<input v-model="form.language" required></label><label>Tahun penciptaan<input v-model="form.creation_year" type="number" min="1900" required></label></div><label>Cerita di balik lagu<textarea v-model="form.story" minlength="50" rows="6" required></textarea></label><label>Lirik lagu<textarea v-model="form.lyrics" rows="8"></textarea></label></template>
<template v-if="step===3"><div class="notice">Gunakan tautan HTTPS yang dapat dibuka tim, atau upload file langsung. Demo dan video tetap wajib tersedia melalui salah satu cara.</div><label>Tautan demo (opsional jika upload)<input v-model="form.demo_url" type="url" placeholder="https://drive.google.com/..."></label><FileDropzone accept="audio/mpeg,audio/wav,audio/mp4,audio/x-m4a" label="Upload demo lagu" hint="Tarik audio ke sini atau klik · MP3, WAV, M4A · Maks. 500 MB" :selected-name="mediaMeta.demo.name" :selected-size="mediaMeta.demo.size" :status="uploads.demo.status" :progress="uploads.demo.progress" :error="uploads.demo.error" @select="uploadLarge($event,'demo')" @remove="cancelUpload('demo')"/><label>Tautan video (opsional jika upload)<input v-model="form.video_url" type="url"></label><FileDropzone accept="video/mp4,video/quicktime" label="Upload video penampilan" hint="Tarik video ke sini atau klik · MP4, MOV · Maks. 500 MB" :selected-name="mediaMeta.video.name" :selected-size="mediaMeta.video.size" :status="uploads.video.status" :progress="uploads.video.progress" :error="uploads.video.error" @select="uploadLarge($event,'video')" @remove="cancelUpload('video')"/></template>
<template v-if="step===4"><label class="check check-all"><input v-model="allAccepted" type="checkbox" aria-describedby="consent-help"><span><b>Centang semua persetujuan</b><small id="consent-help">Kelima persetujuan di bawah wajib disetujui untuk melanjutkan.</small></span></label><div class="consent-divider"></div><label class="check"><input v-model="form.original_work" type="checkbox" required @change="consentError=''"> Karya orisinal dan tidak melanggar hak pihak lain.</label><label class="check"><input v-model="form.rights_approved" type="checkbox" required @change="consentError=''"> Seluruh co-writer/pemilik hak telah setuju.</label><label class="check"><input v-model="form.data_correct" type="checkbox" required @change="consentError=''"> Seluruh data yang saya isi benar.</label><label class="check"><input v-model="form.terms" type="checkbox" required @change="consentError=''"> Saya menyetujui syarat dan kebijakan privasi versi 2026-01.</label><label class="check"><input v-model="form.communication" type="checkbox" required @change="consentError=''"> Saya bersedia menerima komunikasi terkait program.</label><p v-if="consentError" role="alert" class="consent-error">{{consentError}}</p><label>Tanda tangan — tulis nama lengkap<input v-model="form.signature_name" required></label></template>
<template v-if="step===5"><div class="review"><p><span>Nama</span>{{form.full_name}}</p><p><span>Lagu</span>{{form.title}} · {{form.genre}}</p><p><span>Kontak</span>{{form.email}} · {{form.whatsapp}}</p><p><span>Demo</span>{{form.demo_url}}</p></div><p class="text-sm text-neutral-400">Setelah dikirim, data menjadi snapshot dan perubahan hanya dapat dilakukan melalui permintaan revisi.</p></template>
<div v-if="Object.keys(form.errors).length" class="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300"><p v-for="error in form.errors" :key="error">{{error}}</p></div><div class="flex justify-between pt-5"><button v-if="step>1" type="button" class="rounded-full border border-white/20 px-6 py-3" @click="step--">Kembali</button><span v-else></span><button class="cta disabled:cursor-not-allowed disabled:opacity-40" :disabled="form.processing||(step===4&&!allAccepted)">{{step===5?(form.processing?'Mengirim…':'Kirim Demo Sekarang'):'Lanjut →'}}</button></div></form></main></div></template>
<style scoped>label{display:grid;gap:.55rem;font-size:.875rem;font-weight:600}input,textarea{border:1px solid #30302e;background:#181818;border-radius:14px;padding:.9rem 1rem;color:#f7f7f5}input:focus,textarea:focus{outline:2px solid #ff6a00;border-color:transparent}.upload-label{margin-bottom:.55rem;font-size:.875rem;font-weight:600;color:#f7f7f5}.check{display:flex;align-items:flex-start;gap:.8rem;border:1px solid #30302e;border-radius:14px;padding:1rem;cursor:pointer}.check input[type=checkbox]{width:1.25rem;height:1.25rem;min-width:1.25rem;margin-top:.05rem;padding:0;border-radius:.35rem;accent-color:#ff6a00}.check-all{border-color:#ff6a0066;background:#ff6a000d}.check-all span{display:grid;gap:.25rem}.check-all small{color:#a9a9a5;font-weight:400}.consent-divider{height:1px;background:#30302e}.consent-error{border-radius:.75rem;background:#ef44441a;padding:.8rem;color:#fca5a5;font-size:.875rem}.notice{border-left:3px solid #ff6a00;background:#181818;padding:1rem;color:#aaa}.review{display:grid;gap:1rem;border:1px solid #30302e;border-radius:20px;padding:1.5rem}.review p{display:grid;gap:.3rem}.review span{font-size:.7rem;text-transform:uppercase;letter-spacing:.14em;color:#ff6a00}</style>
